"""Add github_username field to Chat

Revision ID: 0f02a7a57103
Revises: ddfb464209cf
Create Date: 2024-10-07 15:21:32.689249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f02a7a57103'
down_revision = 'ddfb464209cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###
