"""Add archived field to Repo

Revision ID: 1bc708e3cc39
Revises: 1e97884ec28a
Create Date: 2024-10-24 12:40:22.324639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc708e3cc39'
down_revision = '1e97884ec28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
