"""Add description field to Repo

Revision ID: 1e97884ec28a
Revises: a0844bd90308
Create Date: 2024-10-17 12:08:59.852987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e97884ec28a'
down_revision = 'a0844bd90308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
